# Use an official Ubuntu image as a parent image
FROM ubuntu:latest

# Set the working directory in the container
WORKDIR /app

# Install ffmpeg and other dependencies
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    
    rm -rf /var/lib/apt/lists/*

# Copy the configuration file for the RTSP server
COPY rtsp-simple-server.yml /app/rtsp-simple-server.yml

# Copy the video file into the container
COPY people.mp4 /app/people.mp4

# Expose RTSP port
EXPOSE 8554

# Run the RTSP server and stream the video
CMD [" ffmpeg -re -stream_loop -1 -i /app/people.mp4 -f rtsp -rtsp_transport tcp rtsp://localhost:8554/live.stream"]

